import { financeStatus } from "../types"

class CashDetailModel{
    id:string
    code:string
    date:Date
    invoice_date:Date
    invoiced_at:string
    major:string
    major_id:string
    type:'IMPORT'|'EXPORT'
    payer_id:string
    payer_name:string
    receiver_id:string
    receiver_name:string
    address:string
    phone:string
    reason:string
    description:string
    deny_reason:string
    value:number
    accountings:any[]
    status:financeStatus
    verify_user:string
    verify_date:string
    create_user:string
    created_at:string
    createdAt:string
    active:boolean
    disabled:boolean
    constructor(
        id:string,
        code:string,
        date:Date,
        invoice_date:Date,
        invoiced_at:string,
        major:string,
        major_id:string,
        type:'IMPORT'|'EXPORT',
        payer_id:string,
        payer_name:string,
        receiver_id:string,
        receiver_name:string,
        address:string,
        phone:string,
        reason:string,
        description:string,
        deny_reason:string,
        value:number,
        accountings:any[],
        status:financeStatus,
        verify_user:string,
        verify_date:string,
        create_user:string,
        created_at:string,
        createdAt:string,
        active:boolean,
        disabled:boolean
    ){
        this.id=id
        this.code=code
        this.date=date
        this.invoice_date=invoice_date,
        this.invoiced_at=invoiced_at,
        this.major=major
        this.major_id=major_id
        this.type=type
        this.payer_id=payer_id
        this.payer_name=payer_name
        this.receiver_id=receiver_id
        this.receiver_name=receiver_name
        this.address=address
        this.phone=phone
        this.reason=reason
        this.description=description
        this.deny_reason=deny_reason
        this.value=value
        this.accountings=accountings
        this.status=status
        this.verify_user=verify_user
        this.verify_date=verify_date
        this.create_user=create_user
        this.created_at=created_at
        this.createdAt=createdAt
        this.active=active
        this.disabled=disabled
    }
    static initial(type:'IMPORT'|'EXPORT'){
        return {
            id:'',
            code:'',
            date:new Date(),
            invoice_date:new Date(),
            invoiced_at:'',
            major:'',
            major_id:'',
            type:type,
            payer_id:'',
            payer_name:'',
            receiver_id:'',
            receiver_name:'',
            address:'',
            phone:'',
            reason:'',
            description:'',
            deny_reason:'',
            value:0,
            accountings:[],
            status:'WAITING' as financeStatus,
            verify_user:'',
            verify_date:'',
            create_user:'',
            created_at:'',
            createdAt:'',
            active:false,
            disabled:false
        }
    }
}
export {CashDetailModel}